# Generated by Django 4.2.5 on 2023-09-24 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_yrok'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
