# Generated by Django 4.2.5 on 2023-09-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_product_delete_yrok'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='Владелец')),
                ('title', models.CharField(max_length=50, verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Yrok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='Владелец')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('video_name', models.CharField(max_length=50, verbose_name='Ссылка на видео')),
                ('view', models.FloatField(max_length=50, verbose_name='Длительность просмотра')),
                ('slug', models.SlugField(default='')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
