# Generated by Django 4.2.5 on 2023-09-24 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_spisok'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Yrok',
        ),
    ]
