# Generated by Django 4.2.5 on 2023-09-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_spisok_yrok'),
    ]

    operations = [
        migrations.AddField(
            model_name='spisok',
            name='yrok',
            field=models.ManyToManyField(to='main.yrok'),
        ),
    ]
