# Generated by Django 4.2.5 on 2023-09-24 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_spisok_yrok'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spisok',
        ),
    ]
