# Generated by Django 4.2.5 on 2023-09-24 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_spisok'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spisok',
            fields=[
                ('yrok_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.yrok')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
            bases=('main.yrok',),
        ),
    ]
