# Generated by Django 4.2.5 on 2023-09-24 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0016_delete_spisok'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spisok',
            fields=[
                ('yrok_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.yrok')),
                ('n', models.CharField(max_length=50, verbose_name='Название')),
                ('vid', models.CharField(max_length=50, verbose_name='Ссылка на видео')),
                ('v', models.FloatField(max_length=50, verbose_name='Длительность просмотра')),
                ('s', models.SlugField(default='')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('u', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('main.yrok',),
        ),
    ]
