# Generated by Django 4.2.5 on 2023-09-24 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_spisok'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spisok',
        ),
    ]
