# Generated by Django 4.2.5 on 2023-09-24 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0018_delete_spisok'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Продукт')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product2',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Yrok2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('video_name', models.CharField(max_length=50, verbose_name='Ссылка на видео')),
                ('view', models.FloatField(max_length=50, verbose_name='Длительность просмотра')),
                ('slug', models.SlugField(default='')),
                ('location_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product2')),
            ],
            options={
                'db_table': 'yrok2',
                'managed': True,
            },
        ),
    ]
