# Generated by Django 4.2.5 on 2023-09-24 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_product2_yrok2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yrok',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Yrok',
        ),
    ]
