# Generated by Django 4.2.5 on 2023-09-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_yrok_user_delete_product_delete_yrok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yrok2',
            name='slug',
            field=models.SlugField(default='Не просмотрено'),
        ),
    ]
