# Generated by Django 4.2.5 on 2023-09-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_yrok2_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yrok2',
            name='slug',
            field=models.SlugField(default='', null=True),
        ),
    ]
