# Generated by Django 4.2.5 on 2023-09-25 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_yrok2_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Yrok2',
        ),
    ]
