# Generated by Django 4.2.5 on 2023-09-25 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_delete_yrok2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yrok2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('video_name', models.CharField(max_length=50, verbose_name='Ссылка на видео')),
                ('view', models.FloatField(max_length=50, verbose_name='Длительность просмотра')),
                ('slug', models.SlugField(default=' ')),
                ('data_field', models.DateField()),
                ('location_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product2')),
            ],
            options={
                'db_table': 'yrok2',
                'managed': True,
            },
        ),
    ]
