# Generated by Django 4.2.5 on 2023-09-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_yrok2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sum_Only',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'sum_only',
                'managed': True,
            },
        ),
    ]
