# Generated by Django 4.2.5 on 2023-09-25 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_sum_only'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sum_Only',
        ),
    ]
